# The port the server will run on
port = 4545
# Which levels are allowed to be logged onto the console. In order of verbosity: "error", "warn", "info", "log"
log_level = ["error", "warning", "info", "log", "debug"]